# Generated by Django 3.2.5 on 2021-07-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['email'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profile'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Full_Name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Mob_Number',
            new_name='mob_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ProfilePhoto',
            new_name='profile_photo',
        ),
    ]
