# Generated by Django 3.2.5 on 2021-12-20 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customapp', '0002_auto_20210703_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mob_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phone number address already exists'}, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number ', regex='^(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Phone Number '),
        ),
    ]
