# Generated by Django 4.0 on 2021-12-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customapp', '0003_alter_userprofile_mob_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
